apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-standard_cluster.vran.ibm.com
  namespace: openshift-gitops
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/standard_cluster.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/gururajpatil313/ocp48-automation.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true