apiVersion: v1
kind: Namespace
metadata:
  name: ocp48-controlplane-cluster-1
  labels:
    name: ocp48-controlplane-cluster-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: common
  labels:
    name: common
    argocd.argoproj.io/managed-by: ocp48-controlplane-cluster-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub 
  labels:
    name: clusters-sub
    argocd.argoproj.io/managed-by: ocp48-controlplane-cluster-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-sub
  labels:
    name: policies-sub
    argocd.argoproj.io/managed-by: ocp48-controlplane-cluster-1
---
apiVersion: v1
data:
  password: NmM0YTE4M2QxNGM0Y2QzM2ZjM2U2MDQwOTExYjVkOWQ3YWFhYTQ1Mw==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2d1cnVyYWpwYXRpbDMxMy9vY3A0OC1hdXRvbWF0aW9uLmdpdA==
  username: Z3VydXJhanBhdGlsMzEz
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-gururajpatil313-ocp48-automation
  namespace: ocp48-controlplane-cluster-1
type: Opaque