apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ocp48-cluster-1-siteconfig
  project: default
  source:
    path: clusters/ocp48-cluster-1.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/gururajpatil313/ocp48-automation.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
