apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    name: vran-ocp-v4.8.18
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.8.18-x86_64
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""