apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ocp48-cluster-1"
  namespace: "ocp48-cluster-1"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.18"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD0HEjx3ULvhRp+qqUY88g/utx9WEwz06mryHcLnVZy3eSTXull7yady/Dg7wt8hr9mQwpS58QuTA/cL3mHa3zkMMiRnd1Nr/VctuXLWo7SxYzf8aCOIMNrldmlUteueZhJsR5EDINk3S8hhAwg3pJPFsyeA6vl5+gq4fC/nC60LFMNx6OZ4j7c1w4T4hV9cdb4PQ6Sbhf3eg5UE8ZMN4t3+kyE6WvOM3Ck/o/TxxaNz1SwTP2wOanG171hSuCUDWjLCs64al2S3xgV3hV90r6I66sQmL2cyYOFg30Sczk8ylBNA9Llnq21Cucg1fLuU/23czhxU+UxqsZZILnaVZT"
  clusters:
  - clusterName: "ocp48-cluster-1"
    clusterType: "standard"
    clusterProfile: "cu"
    numMasters: 3
    numWorkers: 2
    clusterLabels:
      common: true
      sites : "ocp48-cluster-1"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    apiVIP: 9.37.195.38
    ingressVIP: 9.37.195.39
    nodes:
       - hostName: "master-4-ocp48.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.39/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-master-4-ocp48-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:BE:94"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:BE:94"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:BE:94"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ocp48-master-2.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-ocp48-master-2-bmh-secret"
         bootMACAddress: "78:AC:44:22:9B:74"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:9B:74"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:9B:74"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "ocp48-master-3.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.45/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-ocp48-master-3-bmh-secret"
         bootMACAddress: "78:AC:44:22:99:10"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:99:10"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:99:10"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
