apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ocp48-cluster-1"
  namespace: "ocp48-cluster-1"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.18"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiWzSdvX2jmlPwSn4t36TgJVs7V8urfc5FER53d7bd7VW3yHEaVIsRXeuej4fntcH9X3efjCZyfmuuP54g4/S03rZ3bQM+rzngfGs62yoknzJVZB2Po72T/ccUp/TC0AjbaDRkjh/q+3DDTdLo0hj5Jgv9dfW7osB3/2WKnCRObcq2LYQ64ItvRs5Iy7NMJv8EnVuz74ljZ7md5bOD7HOpGxsC3GTVwF+9ixYPgSNudh3fDQhPmQqeZFwXOUoT8bhBhjDUg3/DpPGZj9y5ftNOjNt6zXHRdOwd7kDRb3t4p8fB2ruG/GOuAr0NlIVY8mhJIvn+9oWtdgWjV58jvaNmvJv9T6643+ZI2qn+AZwun33xvWZ+sU7d8s3qPgTNHAaABDUd+PCYsNPsPa1o0+/3Wa1CF7+4m0QSTJ6yW97XsGzDjna0Q1/AAz5/0ZtlHO/sNgJf1Hr/AYJ9jwegf4yyoo3xNT0ckjT+XzzUfN4oYNBDJz9ni+WthSmJPU/n/Dk= root@rhel84-test1.fyre.ibm.com"
  clusters:
  - clusterName: "ocp48-cluster-1"
    clusterType: "standard"
    clusterProfile: "cu"
    numMasters: 3
####    numWorkers: 2
##    clusterLabels:
      common: true
      sites : "ocp48-cluster-1"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    apiVIP: 9.37.195.38
    ingressVIP: 9.37.195.39
    nodes:
       - hostName: "master-4-ocp48.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.39/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-master-4-ocp48-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:BE:94"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:BE:94"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:BE:94"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "master-5-ocp48.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.73/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-master-5-ocp48-bmh-secret"
         bootMACAddress: "78:AC:44:32:7A:D0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:32:7A:D0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:32:7A:D0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
       - hostName: "master-6-ocp48.ocp48-cluster-1.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.45/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "ocp48-cluster-1-master-6-ocp48-bmh-secret"
         bootMACAddress: "78:AC:44:22:99:10"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:99:10"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:99:10"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
