---
apiVersion: v1
data:
  password: Z2hwX1RiY3BzNDdXd1B3UVFXdE05ekRmUUNrTkZITkNXaTNYSTdDUA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2d1cnVyYWpwYXRpbDMxMy9vY3A0OC1hdXRvbWF0aW9uLmdpdA==
  username: Z3VydXJhanBhdGlsMzEz
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-gururajpatil313-ocp48-automation
  namespace: master-1-ocp48
type: Opaque